services:
  optimal-power-time-calculator-web:
    build:
        context: .
        dockerfile: Dockerfile
        target: development
    container_name: optimal_power_time_calculator_web
    stop_signal: SIGINT
    ports:
      - "8000:8000"
    stdin_open: true # docker run -i
    tty: true # docker run -t
    depends_on:
      - optimal-power-time-calculator
    volumes:
      - .:/app

#    entrypoint: ''

  optimal-power-time-calculator:
    image: rasmus256docker/optimalpowertimecalculator:20241031-220616
    container_name: optimal_power_time_calculator
    ports:
      - "8001:80"
    environment:
      - PRICE_CLASS=DK2
    stop_signal: SIGINT
    stdin_open: true # docker run -i
    tty: true # docker run -t
