# Generated by Django 5.1.2 on 2025-04-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='gln_number',
            field=models.CharField(default='TEST', max_length=100),
            preserve_default=False,
        ),
    ]
